version: '3.8'

services:
  # Dịch vụ 1: Backend FastAPI
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      # Ánh xạ thư mục data ở máy thật vào container để không bị mất nhật ký khi tắt Docker
      - ./backend/data:/app/data

  # Dịch vụ 2: Web Frontend
  frontend:
    image: nginx:alpine
    ports:
      - "8080:80" # Truy cập web ở cổng 8080
    volumes:
      # Ánh xạ thư mục frontend của bạn vào đúng chỗ Nginx cần để hiển thị web
      - ./frontend:/usr/share/nginx/html
  
  # Dịch vụ 3: Hệ thống n8n AI
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
    volumes:
      # Tạo một thư mục ảo để n8n lưu dữ liệu nội bộ 
      - ./n8n_setup/n8n_data:/home/node/.n8n